jobs:
  nginx:
    cmd: "/usr/sbin/nginx -c /home/kali/Documents/taskmaster/testing/nginx/nginx.conf"
    numprocs: 1
    umask: 022
    workingdir: /home/kali/Documents/taskmaster/testing/nginx
    autostart: true
    autorestart: true
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 1
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  cat:
    cmd: "/usr/bin/cat ./test"
    numprocs: 1
    umask: 077
    workingdir: /home/kali/Documents/taskmaster/testing/cat
    autostart: false
    autorestart: false
    starttime: 1
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/cat.out
    stderr: /tmp/cat.err

  cat_error:
    cmd: "/usr/bin/cat ./invalid_file"
    numprocs: 1
    umask: 077
    workingdir: /home/kali/Documents/taskmaster/testing/cat
    autostart: false
    autorestart: unexpected
    exitcodes: 0
    starttime: 1
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/cat_error.out
    stderr: /tmp/cat_error.err

  ls:
    cmd: "/usr/bin/ls"
    numprocs: 1
    umask: 077
    workingdir: /tmp
    autostart: false
    autorestart: false
    exitcodes: 0
    starttime: 1
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/ls.out
    stderr: /tmp/ls.err

  sleep_running:
    cmd: "/usr/bin/sleep 10"
    numprocs: 1
    workingdir: 
    umask: 077
    autostart: false
    autorestart: false
    exitcodes: 0
    starttime: 5
    stopsignal: QUIT
    stoptime: 10

  sleep_starting:
    cmd: "/usr/bin/sleep 5"
    numprocs: 1
    umask: 077
    autostart: false
    autorestart: false
    exitcodes: 0
    starttime: 10
    stopsignal: QUIT
    stoptime: 10

  sleep_restarting:
    cmd: "/usr/bin/sleep 5"
    numprocs: 1
    umask: 077
    autostart: false
    autorestart: true
    exitcodes: 0
    starttime: 2
    stopsignal: QUIT
    stoptime: 10

  touch:
    cmd: "/usr/bin/touch miep"
    numprocs: 1
    umask: 000
    workingdir: /tmp
    autostart: false
    autorestart: false
    exitcodes: 0
    starttime: 0
    stopsignal: QUIT
    stoptime: 10
    stderr: /tmp/vgsworker.stderr